smash> smash> smash> smash> smash> smash> smash> regularfile1’s type is "regular file" and takes up 8 bytes
smash> regularfile2’s type is "regular file" and takes up 1 bytes
smash> regularfile3’s type is "regular file" and takes up 44 bytes
smash> folderfile’s type is "directory" and takes up 4096 bytes
smash> /dev/null’s type is "character device" and takes up 0 bytes
smash> /dev/fd’s type is "symbolic link" and takes up 13 bytes
smash> /dev/loop0’s type is "block device" and takes up 0 bytes
smash> /run/acpid.socket’s type is "socket" and takes up 0 bytes
smash> /run/systemd/initctl/fifo’s type is "FIFO" and takes up 0 bytes
smash> smash> smash> smash> smash> smash> smash> 